[package]
name = "bevy-key-rotation"
description = "Access and refresh token rotation for Bevy applications"
license = "MIT/Apache-2.0"
repository = "https://github.com/vectorgameexperts/bevy-key-rotation"
authors = ["Spencer C. Imbleau"]
keywords = ["gamedev"]
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
instant = "0.1"
thiserror = "1.0"
bevy-async-task = "1.2"
async-trait = "0.1"
bevy = { version = "0.11", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
getrandom = { version = "0.2" }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"
getrandom = { version = "0.2", features = ["js"] }
